apiVersion: v1
kind: ConfigMap
metadata:
  name: dogecoin-config
  namespace: {{ .Values.namespace }}
data:
  dogecoin.conf: |-
{{- range $key, $val := .Values.dogecoinConf }}
{{ $key | indent 6}}={{ $val }}
{{- end}}